portainer-ce:
        ports:
            - 8500:8000
            - 9843:9443
            - 9500:9000
        container_name: portainer2
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data2:/data
        image: portainer/portainer-ce:latest
volumes:
    portainer_data2:
        external: true
        name: portainer_data2
